// This file is generated by CLOPS. Do NOT edit. Instead, edit the
// CLOPS input file or the template.
package ie.ucd.clops.dsl.generatedinterface;

public abstract class CLODSLAntTaskBase
    extends org.apache.tools.ant.Task {

  public CLODSLAntTaskBase() throws Exception {
  }
}

