// This file is generated by CLOPS. Do NOT edit. Instead, edit the
// CLOPS input file or the template.
package ie.ucd.clops.dsl.generatedinterface;

public abstract class CLODSLAntTaskBase
    extends org.apache.tools.ant.Task {
  private CLODSLOptionStore options;

  public CLODSLAntTaskBase() throws Exception {
    options = new CLODSLOptionStore();
  }

  public void setOutput(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Output")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Output to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setTest(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Test")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Test to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setOutputPackage(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("OutputPackage")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set OutputPackage to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setDocs(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Docs")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Docs to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setBuiltin(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Builtin")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Builtin to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setCustom(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Custom")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Custom to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setTarget(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Target")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Target to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setStaticCheck(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("StaticCheck")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set StaticCheck to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setVerbose(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Verbose")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Verbose to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setQuiet(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Quiet")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Quiet to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setVersion(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Version")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Version to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setOptionFactory(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("OptionFactory")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set OptionFactory to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setTransitiveFlyRules(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("TransitiveFlyRules")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set TransitiveFlyRules to " + value + ".\n" + 
        "Error: " + e);
    }
  }
  public void setInput(String value) 
  throws org.apache.tools.ant.BuildException {
    try {
      options.getOptionByIdentifier("Input")
        .setFromString(value);
    } catch (Exception e) {
      throw new org.apache.tools.ant.BuildException(
        "Can't set Input to " + value + ".\n" + 
        "Error: " + e);
    }
  }

  @Override
  public void execute() throws org.apache.tools.ant.BuildException {
    run(options);
  }

  public abstract void run(CLODSLOptionsInterface options)
  throws org.apache.tools.ant.BuildException;
}

